name: 🧪 Vérification du Build Astro

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test-build:
    name: Tester la compilation
    runs-on: ubuntu-latest
    
    # Indique à GitHub d'exécuter toutes les commandes dans le dossier site-web
    defaults:
      run:
        working-directory: ./
        
    steps:
      - name: 📥 Récupérer le code
        uses: actions/checkout@v4

      - name: ⚙️ Configurer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './package-lock.json' # Précise où se trouve le fichier de cache

      - name: 📦 Installer les dépendances
        run: npm ci

      - name: 🏗️ Tester le build
        run: npm run build